### ISSUE TITLE
[Bug]: Player unable to open the game from the launcher

### ISSUE THREAD

**Issue by Zunwolf1896** [starfish-studios/Naturalist#10]
### Mod Version

naturalist-fabric-2.0.1-1.19.jar

### Mod Loader

Fabric

### Mod Loader Version

Fabric - 0.14.7

### What happened?

Player opens the game using Curseforge, get the Minecraft launcher to appear, presses play and gets an error - shown below. 

![image](https://user-images.githubusercontent.com/88537204/175771398-fba90550-5ce8-45c0-a709-000e4b6a5b92.png)

### latest.log

https://gist.github.com/Zunwolf1896/47147cbb2f6238a5fc41adf1d3bfdffd#file-crash

**Comment by Space-Unicornn** [comment]
The game was opened through normal Minecraft launcher, not Curseforge. Also it loads for a little and then crashes.
-The player who crashed

**Comment by samedifferent** [comment]
You forgot to install Geckolib: https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3844301

**Comment by Space-Unicornn** [comment]
I have geckolib on. The only time the game loads is if I load it through Curseforge (and the Curseforge on my main computer doesn't work.)

**Comment by Synthestra** [comment]
Did you install the fabric geckolib? according to your modlist, it isn't registered

**Comment by samedifferent** [comment]
What is the name of the geckolib jar file that you are using?

**Comment by Space-Unicornn** [comment]
Oh I think it's working now. Thanks!
