### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by legosteenjaap** [starfish-studios/Naturalist#12]
### Mod Version

2.0.1

### Mod Loader

Forge

### Mod Loader Version

41.0.62

### What happened?

The game crashes on startup.

### latest.log

https://paste.ee/p/BBoFB

**Comment by samedifferent** [comment]
You do not have Geckolib installed, which is a required dependency. Download it here: https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3847903
