### ISSUE TITLE
[Bug]: says the mod failed to load correctly, followed by java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by Reecimo** [starfish-studios/Naturalist#13]
### Mod Version

2.0.1

### Mod Loader

Forge

### Mod Loader Version

41.0.63

### What happened?

Tried to load up the game to see this error, i have GeckoLib installed, I dont know what else i can do.

I put both crash log and latest log in the attachments.

### latest.log

[latest.log](https://github.com/starfish-studios/Naturalist/files/9066130/latest.log)
[crash-2022-07-07_18.30.21-fml.txt](https://github.com/starfish-studios/Naturalist/files/9066137/crash-2022-07-07_18.30.21-fml.txt)

**Comment by samedifferent** [comment]
The error means that you don't have the correct version of geckolib installed. You need to use the version for Forge 1.19. You are probably using the quilt or fabric version of geckolib. Here is the forge version: https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3856642
