### ISSUE TITLE
[Bug]: Flying pigs?

### ISSUE THREAD

**Issue by ProgrammingParadox** [starfish-studios/Naturalist#14]
### Mod Version

2.0.1-1.19

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### What happened?

So, I downloaded the mod onto a local minecraft server at the request of my younger brother. Much to my horror, after loading up the game I was met with the sight of **flying pigs!** I was very confused at first, but came to the conclusion that it was probably a bird that had failed to load properly. I started another world on the server and ended up with (gasp) the same shocking sight! Some have saddles but are sadly unridable. (Well, what was I expecting?)

![image](https://user-images.githubusercontent.com/73145304/177843335-3a5ce3c0-6e51-4212-8150-6408b2b66f9c.png)
![image](https://user-images.githubusercontent.com/73145304/177843354-fb67ac32-f95b-4c79-9deb-5e72c0ab83be.png)
![image](https://user-images.githubusercontent.com/73145304/177843368-b57a3c3d-60c1-472c-bde2-5e91eb5f38ec.png)

### latest.log

[latest.log](https://github.com/starfish-studios/Naturalist/files/9066385/latest.log)

(The only mods on the server are Geckolib and Naturalist)

**Comment by samedifferent** [comment]
This is quite strange and I have no idea why this is happening. Does the server have any plugins? In the report you wrote that your client is using fabric loader version 0.11.0, which is pretty old, so I would first try updating to the latest one which is 0.14.8.

**Comment by samedifferent** [comment]
Maybe this is a Geckolib bug. Can you try removing Naturalist and just use GeckoLib, and see if the issue persists?

**Comment by samedifferent** [comment]
I asked in the Geckolib server and they said this is likely caused by a bad install on your end. I can't reproduce the issue myself on a server, so it doesn't look like it's an issue with the mods themselves. Try reinstalling Fabric.

**Comment by ProgrammingParadox** [comment]
That didn't seem to work. The bears are still pigs. 😞 

Is there a special way I'm supposed to install Geckolib on a minecraft server? Right now I just have the `.jar` file in the mod folder along with the fabric API and Naturalist `.jar`s.

**Comment by Fuzss** [comment]
Hey there, this issue is caused by Naturalist missing on the client. This is already visible from the client apparently not knowing the translation key `entity.naturalist.bear`.
Pigs are the default entry in the entity type registry, so an unknown entity will appear as a pig on the client.
Fabric doesn't unfortunately seem to check if registries match when a client is connecting to the server, I'm not sure if something can be done about this.
