### ISSUE TITLE
[Bug]: Crash with Physics mod installed.

### ISSUE THREAD

**Issue by murao-kun** [starfish-studios/Naturalist#20]
### Mod Version

2.0.2

### Mod Loader

Forge

### Mod Loader Version

42.0.1

### What happened?

When I kill creature with Physics mod installed client crashing.

### latest.log

[crash-2022-08-03_17.12.52-client.txt](https://github.com/starfish-studios/Naturalist/files/9252652/crash-2022-08-03_17.12.52-client.txt)
[crash-2022-08-03_17.24.17-client.txt](https://github.com/starfish-studios/Naturalist/files/9252653/crash-2022-08-03_17.24.17-client.txt)

**Comment by murao-kun** [comment]
https://github.com/haubna/PhysicsMod/issues/417

**Comment by samedifferent** [comment]
This is a geckolib incompatibility with architectury projects, but the architectury developer managed to find a temporary fix, which I applied here https://github.com/starfish-studios/Naturalist/commit/e608802c573d63353e454737145fcca7942c6d65
This will be fixed in the next update.
