### ISSUE TITLE
[Bug]: Naturalist and Statement Library are crashing on fabric 1.19x

### ISSUE THREAD

**Issue by nickademas** [starfish-studios/Naturalist#26]
### Mod Version

naturalist-fabric-2.1.1-1.19.2.jar

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### What happened?

^

### latest.log

https://gist.github.com/nickademas/176bea9df779eed7df35127b97d9b80b

**Comment by samedifferent** [comment]
Please send the full log file.

**Comment by nickademas** [comment]
[crash-2022-08-22_22.53.47-client.txt](https://github.com/starfish-studios/Naturalist/files/9410874/crash-2022-08-22_22.53.47-client.txt)
[2022-08-22-1.log.gz](https://github.com/starfish-studios/Naturalist/files/9410877/2022-08-22-1.log.gz)

**Comment by Zarepheth** [comment]
I'm suffering the same error, probably because the "Statement" library is also installed in my Curse Forge profile.
[crash-2022-11-25_14.51.53-client.txt](https://github.com/starfish-studios/Naturalist/files/10095062/crash-2022-11-25_14.51.53-client.txt)

**Comment by Zarepheth** [comment]
Turning off the Statement library also turns off [Wart Decay](https://www.curseforge.com/minecraft/mc-mods/wart-decay).

**Comment by JoelZBub** [comment]
It's nice this was fixed. Could it be applied to a jar that gets uploaded to Curseforge so we can use it, please?
