### ISSUE TITLE
[Bug]: Incompatibility with Solid Mobs

### ISSUE THREAD

**Issue by CheezBallzFTW** [starfish-studios/Naturalist#34]
### Mod Version

2.1.1

### Mod Loader

Fabric

### Mod Loader Version

0.14.10

### What happened?

Rhino can't hit me with charge because of solid mobs.

### latest.log

https://gist.github.com/CheezBallzFTW/ecd6852aecf62c42bbd1b6f4c4d22c93

**Comment by Sunconure11** [comment]
https://github.com/Traben-0/solid_mobs

Here's the repo for this mod. @Synthestra

**Comment by crispytwig** [comment]
> https://github.com/Traben-0/solid_mobs
> 
> Here's the repo for this mod. @Synthestra

Synthestra is not a Naturalist developer, and this issue will need to be reported to Solid Mobs as it is not an issue caused by Naturalist. Thank you!

**Comment by Sunconure11** [comment]
@CheezBallzFTW The mod has a blacklist, add the mob to such.
