### ISSUE TITLE
[Bug]: Elephant head changing size in game

### ISSUE THREAD

**Issue by DEAFG0AT** [starfish-studios/Naturalist#40]
### Mod Version

1.19.2

### Mod Loader

Fabric

### Mod Loader Version

0.73.2

### What happened?

Elephant heads change sizes randomly in-game. The also move their legs without walking and walk without moving their legs. Dirt appears on them without their trunks moving. I understand this would normally be an out-of-date Geckolib, but I'm fully updated on everything. I'm launching a server next month and would love to keep this mod!

https://user-images.githubusercontent.com/104733108/221269121-83a05506-e524-4a87-b870-213343e9b2bc.mp4

### latest.log

No crash, no log

**Comment by WuschelWookie** [comment]
I am having the same issue on forge with other mobs like the rhino or bear.

**Comment by Khytwel** [comment]
Same issue and it also happens on lion (I use fabric in 1.19.2). I would like to specify that I use Iris on my side with shader enabled (Complementary Reimagined Shaders).

**Comment by LonelyBard** [comment]
> Same issue and it also happens on lion (I use fabric in 1.19.2). I would like to specify that I use Iris on my side with shader enabled (Complementary Reimagined Shaders).



> I am having the same issue on forge with other mobs like the rhino or bear.



> ### Mod Version
> 1.19.2
> 
> ### Mod Loader
> Fabric
> 
> ### Mod Loader Version
> 0.73.2
> 
> ### What happened?
> Elephant heads change sizes randomly in-game. The also move their legs without walking and walk without moving their legs. Dirt appears on them without their trunks moving. I understand this would normally be an out-of-date Geckolib, but I'm fully updated on everything. I'm launching a server next month and would love to keep this mod!
> 
>  naturalist_elephant_bug_1.mp4 
> ### latest.log
> No crash, no log

If yall are using shaders, try turning off "Entity Shadows." this fixed the issue for me
