### ISSUE TITLE
[Bug]: Mod failed to load correctly, followed by java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by jasonpeterson444** [starfish-studios/Naturalist#42]
### Mod Version

forge-2.1.1-1.19.2

### Mod Loader

Forge

### Mod Loader Version

forge-1.19.3-44.1.0

### What happened?

Mod failed to load correctly, followed by java.lang.reflect.InvocationTargetException: null 
error message

I uploaded the latest log.

I am stumped. Any insight?

### latest.log

[Naturalist error log.txt](https://github.com/starfish-studios/Naturalist/files/10964520/Naturalist.error.log.txt)

**Comment by Synthestra** [comment]
use mc 1.19.2
