### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Lozf** [starfish-studios/Naturalist#5]
### Mod Version

1.0.1

### Mod Loader

Fabric

### Mod Loader Version

0.14.6

### What happened?

So the bears sometimes sleep when day properly or will just stand frozen, they move around at night but most slide.  Some do walk.  The butterflies rarely flap, the same with the fireflies, the birds seem fine- by the way they, how they stare at small animals is so great!  In the earlier version they didn't flap all the time when they flew but in the latest version birds flapping seems fixed.  Snakes if they have to turn around while they are following something seem to get stuck just going in a circle on the same block.  Some deer, like bears, walk properly and eat properly but most just slide around.   Some start out walking properly, once they go up or down a block they then start sliding.  The eating animation only works for the ones that are walking.

### latest.log

https://gist.github.com/Lozf/82e3e87864023551b8ce961bfe967827

**Comment by samedifferent** [comment]
I can't seem to reproduce this sliding issue. Can you see if you can reproduce the issue using just Naturalist and Geckolib, with no other mods installed? Also, a video would be helpful since I'm having trouble understanding what you mean.

**Comment by Lozf** [comment]
Sure, I am working through finals atm so it will be a little bit.  By slide I mean their legs are all straight but they still move around.  With the butterflies/fireflies, they still move normally but the wings do not flap.  Is there a preferred version for Geckolib?  I am using the latest version.

**Comment by Lozf** [comment]
Ok so this is not reproducible with only naturalist and geckolib.  I will do some testing later to figure out what it's not working with.

**Comment by samedifferent** [comment]
If you have any performance-enhancing mods installed, I would first try removing those. They cause issues like this more often than normal content-adding mods.

**Comment by Lozf** [comment]
Thank you, I will try that first for sure!

**Comment by Lozf** [comment]
So this might actually be complementary shaders, or maybe something in iris that gets triggered when I toggle shaders on and off?  I tried the performance-enhancing off, then thought sweet, that was it, toggled shaders on and the problem occurred.

**Comment by samedifferent** [comment]
I just confirmed in the Geckolib discord server that this is a shaders issue, other people are experiencing this with other Geckolib-powered mods. I don't think there's anything I can do on my end to fix it.

**Comment by Lozf** [comment]
Ok, thank you.
