### ISSUE TITLE
[Bug]: Shader's with Entity shadows cause large head and broken walking animations

### ISSUE THREAD

**Issue by LonelyBard** [starfish-studios/Naturalist#50]
### Mod Version

3.0.0

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### What happened?

Your mod has a rendering issue causing the heads of animals to be large randomly and also breaking walking animations when using shaders that apply Entity shadows. Turning off the setting fixes the issue.

For reference, I'm using Complementary Reimagined r1.3.2 with Iris 1.6.0 

### latest.log

[latest.log](https://github.com/starfish-studios/Naturalist/files/11277994/latest.log)

**Comment by crispytwig** [comment]
This is not an issue with Naturalist and has already been reported to the GeckoLib developer. Thank you!
