### ISSUE TITLE
[Bug]: Firefly spawn rates are absurd

### ISSUE THREAD

**Issue by Sunconure11** [starfish-studios/Naturalist#52]
### Mod Version

3.0.1

### Mod Loader

Fabric

### Mod Loader Version

Quilt Beta 0.19

### What happened?

![image](https://user-images.githubusercontent.com/5614902/233465031-3b945ee8-3c48-4196-ab18-6b98265bb92a.png)

### latest.log

N/A

**Comment by Castorizzando** [comment]
Tried the same here, i even tried to set the spawn rate to -100 but nothing worked, except removing the mod.

I think they want my soul.
![image](https://user-images.githubusercontent.com/131290911/233537134-b41aadf0-1467-4694-af84-eb8886b8bc84.png)

**Comment by Sunconure11** [comment]
@Synthestra

**Comment by crispytwig** [comment]
> @Synthestra

This was fixed in version 3.0.3 on Fabric and Forge, although the bug only seemed to happen on Fabric. Apologies for the late response.
