### ISSUE TITLE
[Crash]: Crash when loading server

### ISSUE THREAD

**Issue by zrll12** [starfish-studios/Naturalist#54]
### Mod Version

1.1.1-1.18.2

### Mod Loader

Forge

### Mod Loader Version

40.2.1(with CatServer 1.18.2-08dc0b6f)

### What happened?

The server crashed when loading.

### latest.log

[crash-2023-04-22_22.48.52-server.txt](https://github.com/starfish-studios/Naturalist/files/11301589/crash-2023-04-22_22.48.52-server.txt)

**Comment by crispytwig** [comment]
Sorry for the late response; we need your latest.log, not your crash report. Thank you!

**Comment by crispytwig** [comment]
Looking back at this and skimming over the crash report, it seems to be a mod conflict with https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick .

Uninstall that mod and feel free to open a new issue if it persists afterwards.
