### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jackk225** [starfish-studios/Naturalist#55]
### Mod Version

3.0.1

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### What happened?

The ducks are laying chicken eggs. Breeding them with seeds works, but there seems to be no way to get duck eggs.

### latest.log

idk how to do that sorry

**Comment by crispytwig** [comment]
This is fixed in version 3.0.4, which will be uploaded after we fix a few more things. Thank you for your report!
