### ISSUE TITLE
[Bug]: Coral Snakes spawn on Snowy Beaches

### ISSUE THREAD

**Issue by dabomb6405** [starfish-studios/Naturalist#6]
### Mod Version

1.0.3

### Mod Loader

Forge

### Mod Loader Version

40.1.25

### What happened?

Coral Snakes seem to be spawning on snowy beaches, which is a place I don't really think a tropical species of snake should be found. 

### latest.log

[latest.log](https://github.com/starfish-studios/Naturalist/files/8850224/latest.log)

**Comment by samedifferent** [comment]
Fixed in https://github.com/starfish-studios/Naturalist/commit/a5f172195836a310f956dfe98bc0e4379cf4703a
