### ISSUE TITLE
[Bug]: Duck Egg does not get thrown by Dispenser

### ISSUE THREAD

**Issue by Dekamir** [starfish-studios/Naturalist#60]
### Mod Version

3.0.2

### Mod Loader

Fabric

### Mod Loader Version

0.14.19

### What happened?

Duck Eggs, when loaded and used via a Dİspenser, does drop itself instead of getting thrown, like Chicken Eggs (vanilla).

### latest.log

[latest.log](https://github.com/starfish-studios/Naturalist/files/11482636/latest.log)

**Comment by crispytwig** [comment]
This has been fixed and will be implemented in the upcoming patch, Naturalist 3.0.3. Thanks for letting us know about this bug!
