### ISSUE TITLE
[Bug]: Glass Tag

### ISSUE THREAD

**Issue by celsiusqc** [starfish-studios/Naturalist#61]
### Mod Version

3.0.2

### Mod Loader

Forge

### Mod Loader Version

43.2.10

### What happened?

Please add the #forge:glass and #forge:glass/colorless tags to the glass forthis mod.

### latest.log

d

**Comment by crispytwig** [comment]
This has been implemented and will be present in Naturalist 3.0.3 when uploaded to CurseForge and Modrinth. Thank you for the suggestion!
