### ISSUE TITLE
[Incorrect Tag]: Bass and Catfish don't use correct tags

### ISSUE THREAD

**Issue by Atirtra** [starfish-studios/Naturalist#63]
### Mod Version

3.0.3a

### Mod Loader

Fabric

### Mod Loader Version

14.21

### What happened?

Raw Bass and Catfish use the wrong "c" tag #c:raw_fish, when vanilla fishes use the tag #c:raw_fishes. This is an issue because other mods using raw fish in their features or recipes like Farmer's Delight can't utilize these fishes in them at all.
![Näyttökuva (15)](https://github.com/starfish-studios/Naturalist/assets/110634509/d93eb60f-1b9a-439f-b2d9-bc49ee609325)
![Näyttökuva (16)](https://github.com/starfish-studios/Naturalist/assets/110634509/d0617639-2dfd-4839-9859-c57dad78fde8)

However, searching only "#fishes" finds them correctly
![Näyttökuva (20)](https://github.com/starfish-studios/Naturalist/assets/110634509/7a6dc703-102a-4271-a017-288e249b01f9)

So that's why this type of stuff isn't working.
![Näyttökuva (26)](https://github.com/starfish-studios/Naturalist/assets/110634509/6c29af53-89af-44a2-811a-3b01487cf3d1)

### latest.log

[latest.log](https://github.com/starfish-studios/Naturalist/files/11687723/latest.log)

(This is useless with this problem)

**Comment by crispytwig** [comment]
Sorry, I meant to close this with a comment. This has been fixed and will be included in the next update, thanks for bringing it to our attention!
