### ISSUE TITLE
cant feed caterpillars flowers

### ISSUE THREAD

**Issue by immortal-cabbage** [starfish-studios/Naturalist#8]
caterpillars arent able to be fed flowers to speed up their time to find a tree

**Comment by immortal-cabbage** [comment]
? no input at all?

**Comment by samedifferent** [comment]
If you look closely, you will see that the issue was closed "as completed in https://github.com/starfish-studios/Naturalist/commit/9766756b5a3b9053554abd5ba005cc6256846b15" which means it was fixed in that commit. It will make its way into the next available release.
